language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - pip install pylint flake8 coveralls
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-package telegram/
  - flake8 telegram
  - 'if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pylint -E telegram; fi'
after_success:
  coveralls
